# *Python* Data Science introdução

## Pacotes

In [ ]:
import random as rnd
import numpy as np

## Operações básicas

In [ ]:
2+2

4

In [ ]:
4-3

1

In [ ]:
5*32

160

In [ ]:
76/21

3.619047619047619

In [ ]:
4**4

256

## Funções

In [ ]:
def minha_fun_potencia(x, potencia):

  return x**potencia

In [ ]:
minha_fun_potencia(2,4)

16

## Criação de vetores/listas

In [ ]:
vetor1 = [1, 5, 7, 3, 8, 10]
vetor1

[1, 5, 7, 3, 8, 10]

In [ ]:
vetor2 = list(range(6))
vetor2

[0, 1, 2, 3, 4, 5]

In [ ]:
rnd.seed(123)
vetor_aleatorio_0_1 = [round(rnd.uniform(0,1),4) for i in range(5)]
vetor_aleatorio_0_1

[0.0524, 0.0872, 0.4072, 0.1077, 0.9012]

In [ ]:
vetor_aleatorio_inteiros = rnd.sample(range(10,100), 5)
vetor_aleatorio_inteiros

[53, 16, 30, 27, 81]

## Operações com vetores

In [ ]:
np.array(vetor1)+np.array(vetor2)

array([ 1,  6,  9,  6, 12, 15])

In [ ]:
np.array(vetor1)*np.array(vetor2)

array([ 0,  5, 14,  9, 32, 50])

## Operações com matrizes

- Criar matriz

In [ ]:
matrizA = np.array([[2,3], [1,4]])
matrizA

array([[2, 3],
       [1, 4]])

In [ ]:
matrizB = np.random.rand(2,2)
matrizB

array([[0.41148688, 0.44283629],
       [0.35156835, 0.65167443]])

- Operações

In [ ]:
matrizA+matrizB

array([[2.41148688, 3.44283629],
       [1.35156835, 4.65167443]])

In [ ]:
matrizA*matrizB

array([[0.82297377, 1.32850886],
       [0.35156835, 2.60669771]])

In [ ]:
matrizA.dot(matrizB)

array([[1.87767881, 2.84069586],
       [1.81776028, 3.049534  ]])